### PR TITLE
Fix eslint errors

### PR DESCRIPTION
**Pull request by aabdaab**
Fix eslint errors that prevent from merging develop to other branches; remove unused dependencies and use `useCallback` in the filters file (there was an issue before with using that hook but after refactoring it no longer persists 🎉 )

### CODE REVIEW

**Review by kfilip94 — APPROVED** [review]
@aabdaab LGTM!
I'm still not sure if wouldn't be better to disable the line `react-hooks/exhaustive-deps` in .eslintrc.json but I'm perfectly fine with merging this PR :+1:

**Comment by sorodrigo** [comment]
I don't wish to block you merging this, so feel free to merge ✌️ . I have some feedback:

- Instead of using `enabledYears` as a state, consider using it as derived state. Depending on the cost of calculating this you can have it as a local variable within the render function or a memoized value using `useMemo`. I know it's a subtle change, but it's the difference between having to worry about updating the value imperatively or having it recalculated on props change.

- Another place where you might take advantage of using a derived state is in the scenario value, if you create a new value that derives from the selected scenario and the fetched scenarios. When the scenarios are fetched your scenario will be automatically recalculated, avoiding you the need to call `useEffect` to imperatively set a default state. And also removing the need to memoize the internal methods with `useCallback`.

- On another note, perhaps you don't need `useCallback` hook. This is generally aimed at performance optimizations when passing a callback to a child component, and most of the times can be either avoided or replaced with `useReducer`. For this particular case, because you're mainly using pure functions, I'd say that you could take them out of the render function ensuring they wont change. This would leave you with only one `useCallback` for the scenarios, which you may not need if you get rid of the `useEffect`.

**Comment by aabdaab** [comment]
hey @sorodrigo thank you for the feedback, it's super interesting! I don't like that approach with the `useEffect` but didn't have a better idea. I wanted to use `reselect` but it wouldn't simplify since we're not using any global state. I will check your approach, thanks a lot! 💯

**Comment by aabdaab** [comment]
Hey @sorodrigo ready again ☝️
1) I removed `useEffect` and `useState` completely and used `useMemo` to recompute the values. So on the initial load, I'm not setting url params as I did before but rather recomputing the props based on what I get from the API. Then, when interacting with the dropdowns, I set the query params and the props get recalculated accordingly.
2) I moved the pure functions out of the render body and put them into a `utils` file. I don't need to wrap them in the `useCallback` anymore.
3) In the end, I think it really made the code more declarative and simplified things. On the other hand, I'm not sure if I like how the useMemos are used all around the file. I guess that now I see your point about hooks being all over the place :P 

Also, passing along an article that sums things up in a nice concise way: https://benmccormick.org/2019/06/24/derived-state

**Comment by aabdaab** [comment]
Actually, I'm thinking now if it won't create a problem that we don't have a state in the url on the initial load. Because we will have to duplicate the logic in a component that will need these filters values (chart, map, timeline?)

**Comment by aabdaab** [comment]
Another option would be to make filters a parent component and pass the props down to its children (dropdowns, chart, timeline)
```
<Filters />
    <Chart />
    <Map />
    <Timeline />
    ...
</Filters>
```

**Comment by sorodrigo** [comment]
> Actually, I'm thinking now if it won't create a problem that we don't have a state in the url on the initial load. Because we will have to duplicate the logic in a component that will need these filters values (chart, map, timeline?)

Passing them to the children is an option, but I think then the component in charge of this logic wouldnt be the `<Filters />` but maybe it's parent? The Page component?, The App component? I'd say, let's worry about it, when we get there. Great job, I think the code is waaaay simpler now (which is a good thing). You could create custom hooks for the useMemo's and that would maybe make the code more readable, but IMHO right now its great as it is.

Thanks for sharing the link, I will check it out. In my opinion keeping derived state as derived state is one of the most important things: avoids bugs and makes things scale. 💯

**Pull request merged**
