### PR TITLE
Feature/map distribution page

### PR DESCRIPTION
**Pull request by kfilip94**
[PIVOTAL](https://www.pivotaltracker.com/story/show/169209916) | [LIVE DEMO](https://copernicus-forest-git-feature-map-distribution-page.vizzuality1.now.sh/)

This PR:
- implements the first iteration of `Map distribution page` with two maps that are sharing the viewport property,
- introduces design changes in the `Species distribution` page,
- adds toggle species list feature,

ymqjc-05ome

@fannycc I can do a quick gif demo with the tree icon instead of an arrow, but I need this icon in assets folder :)

### CODE REVIEW

**Comment by sorodrigo** [comment]
Could we change the scroll in the species list to `overflow: auto;`?

**Comment by kfilip94** [comment]
@sorodrigo sure :+1:

**Comment by fannycc** [comment]
Hey Kamil! regarding the icon it's in the UI KIT with the all the rest ones :) 
About this page just a couple of comments; I'm guessing I shouldn't review the first nav bar (but just in case, align with the newest design with the logo and so.) Also I agree with Rodrigo's comment about that ugly scrolling bar 👍 
The rest looks good so far, I'm very keen to see how the legends looks here ! good job

**Comment by sorodrigo** [comment]
Another comment, please use icomoon 🙇

**Comment by kfilip94** [comment]
@fannycc 
The main navbar wasn't a part of this PR, but I'll create a task in Pivotal for adjusting the styles with the design :+1: 
Below you can find two gifs with a different version of collapse icon:
559x9-yntbj
6k5da-imisw
Let me know which one do you prefer ;)
About the scrollbar: do you want me to hide it permanently or just show it when there is a content to scroll?

@sorodrigo I'll update the icomoon asap, thanks :+1:

**Comment by fannycc** [comment]
Thanks for the 2 options @kfilip94 ! There are some hard moments in life when I realized that what I considered very cool is actually less intuitive so maybe we need to get rid of the cuteness here and go with the basic arrow :( what do you think?

**Comment by aabdaab** [comment]
On species summary, there's an issue with content getting out of view port and the page being scrollable:
image
instead of the species content being scrollable:
image

Just add `overflow-y: scroll` to `.l-page` class in the layout.scss to fix that issue

**Comment by fannycc** [comment]
ups sorry I didn't answer the scroll bit. I'd go for: `just show it when there is a content to scroll ` So your second option

**Comment by kfilip94** [comment]
@fannycc I'd go with a left/right arrow, it seems to be more intuitive :)
@aabdaab Thanks for spotting this, fixed :man_factory_worker:

**Review by aabdaab — APPROVED** [review]
Thanks for the changes and for the effort in this PR!

**Pull request merged**
